sentimentBotReplyComment: >
  Please be sure to review the code of conduct and be respectful of other users. /cc @Videndum/moderators

requestInfoReplyComment:
 - Ah no! young blade! That was a trifle short!
 - Tell me more!
 - I am sure you can be more effusive

entimentBotToxicityThreshold: .7
requestInfoLabelToAdd: "More information needed"
checkIssueTemplate: true
checkPullRequestTemplate: true
requestInfoOn:
  pullRequest: true
  issue: true
requestInfoUserstoExclude:
  - ${{github.rerepository_owner}}

