
mode: auto
silent: false
branchName: '${issue.number}-${issue.title}'
autoCloseIssue: true
branches:
    - label: 'Type: Chore'
      prefix: chore/
    - label: 'Type: Enhancement'
      prefix: feature/
    - label: 'Type: Feature'
      prefix: feature/
    - label: 'Type: Documentation'
      prefix: docs/
    - label: 'Type: Bug'
      prefix: issue/
    - label: 'Type: Maintenance'
      prefix: maintenance/
    - label: 'Type: Optimisation'
      prefix: maintenance/
    - label: 'Type: Refactor'
      prefix: maintenance/
    - label: 'Type: Style'
      prefix: maintenance/
    - label: 'Type: Discussion'
      skip: true
    - label: 'Type: Question'
      skip: true
    - label: 'Type: Revert'
      skip: true
    - label: '*'
      prefix: issue/

