mode: auto
silent: false
branchName: '${issue.number}-${issue.title}'
autoCloseIssue: true
branches:
  - label: 'Type - Chore'
    prefix: chore/
  - label: 'Type - Enhancement'
    prefix: enhance/
  - label: 'Type - Feature'
    prefix: feat/
  - label: 'Type - Documentation'
    prefix: docs/
  - label: 'Type - Bug'
    prefix: bug/
  - label: 'Type - Maintenance'
    prefix: maint/
  - label: 'Type - Optimisation'
    prefix: opt/
  - label: 'Type - Decrecated'
    prefix: dep/
  - label: 'Type - Refactor'
    prefix: ref/
  - label: 'Type - Style'
    prefix: style/
  - label: 'Type - Discussion'
    skip: true
  - label: 'Type - Question'
    skip: true
  - label: 'Type - Revert'
    skip: true
  - label: '*'
    prefix: issue/
