# Used by issues
"Type - Chore":
  - "chore"
"Type - Enhancement":
  - "enhancement"
  - "enhance"
"Type - Feature":
  - "feature"
  - "feat"
"Type - Documentation":
  - "docs"
"Type - Bug":
  - "bug"
"Type - Maintenance":
  - "maintenance"
  - "maint"
"Type - Optimisation":
  - "optimisation"
  - "opt"
"Type - Decrecated":
  - "decrecated"
  - "dep"
"Type - Refactor":
  - "refactor"
  - "ref"
"Type - Style":
  - "style"
  - "style"
"Type - Revert":
  - "revert"
