## This defines which lables should be applied to each PR
## {lable}: {branches}

'Type - Chore': 'chore/*'
'Type - Enhancement': 'enhance/*'
'Type - Feature': 'feat/*'
'Type - Documentation': 'docs/*'
'Type - Fix': 'bug/*'
'Type - Maintenance': 'maint/*'
'Type - Optimisation': 'opt/*'
'Type - Decrecated': 'dep/*'
'Type - Refactor': 'ref/*'
'Type - Style': 'style/*'
'Type - Revert': 'revert/*'
