# Both https://github.com/ilyam8/periodic-pr-labeler & https://github.com/actions/labeler are configured here. Be careful to ensure you use the correct format as documented

'Type - Documentation':
    - docs/**/*
    - README.md
    - CHANGELOG.md
    - LICENSE.md
    - SECURITY.md
'Type - Chore':
    - contributing.json
    - .github/**/*
    - .all-contributorsrc
    - .gitignore
    - .whitesource
    - package.json
    - package-lock.json

'Content - Workflow & CI':
    - contributing.json
    - .github/**/*
    - .all-contributorsrc
    - .gitignore
    - .whitesource
'Content - Dependences':
    - package.json
    - package-lock.json
