name: Project Card Event
on:
  project_card:
    types: [created, moved]
jobs:
  triage:
    name: Auto card labeler
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-card-labeler@v1
