name: Contributor License Agreement Management
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, closed, synchronize]

# Ensures the CLA is signed
jobs:
  CLAssistant:
    name: "CLA Assistant"
    runs-on: ubuntu-latest
    if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA' || github.event_name == 'pull_request' )
    steps:
      - uses: technote-space/load-config-action@v1
        with:
          CONFIG_FILENAME: allconfig.yml
      - run: if [ ${{env.claPush}} == 'head' ]; then echo ::set-env name=claBranch::${{github.head_ref}} ; else echo ::set-env name=claBranch::${{env.claPush}} ; fi
      - name: Checkout
        if: ${{env.claEnabled}} == true
        id: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: CLA Assistant
        if: ${{env.claEnabled}} == true
        uses: cla-assistant/github-action@v1.3.0-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: ${{env.claPath}}
          path-To-cladocument: "https://github.com/${{github.repository}}/${{env.claDocs}}"
          branch: ${{env.claBranch}}
          label: ${{env.claLabel}}
          whitelist: bot*
