name: Contributor License Agreement Management
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, closed, synchronize]

# Ensures the CLA is signed
jobs:
  CLAssistant:
    name: "CLA Assistant"
    runs-on: ubuntu-latest
    if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA' || github.event_name == 'pull_request' )
    steps:
      - uses: technote-space/load-config-action@v1
        with:
          CONFIG_FILENAME: allconfig.yml
      - uses: peterjgrainger/action-create-branch@2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{env.autoBranchPrefix}}${{env.autoBranch}}_CLA
      - name: CLA Assistant
        if: ${{env.claEnabled}} == true
        uses: cla-assistant/github-action@v1.3.0-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: "${{env.claPath}}"
          path-To-cladocument: "https://github.com/${{github.repository}}/${{env.claDocs}}"
          branch: ${{env.autoBranchPrefix}}${{env.autoBranch}}_CLA
          label: ${{env.claLabel}}
          whitelist: ${{env.autoWhitelist}}
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          source_branch: ${{env.autoBranchPrefix}}${{env.autoBranch}}_CLA
          destination_branch: ${{env.autoDestination}}
          pr_title: ${{env.claPRtitle}}
          pr_body: ${{env.autoBody}}
          pr_label: ${{env.autoLabels}}
        continue-on-error: true

