name: Contributor License Agreement Management
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]

# Ensures the CLA is signed
jobs:
  CLAssistant:
    name: 'CLA Assistant'
    runs-on: ubuntu-latest
    if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA' || github.event_name == 'pull_request' )
    steps:
      - name: Manage Github Secrets
        uses: Videndum/manage-github-secrets@1.0.0-beta
        with:
          settings: ${{ secrets.SETTINGS }}
          settingsjson: '.github/allconfigs.json'
          mode: 'environment'
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: peterjgrainger/action-create-branch@2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{env.auto_branchPrefix}}${{env.auto_branch}}_CLA
      - name: CLA Assistant
        if: ${{env.cla_enabled}} == true
        uses: cla-assistant/github-action@v2.0.0-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: '${{env.cla_path}}'
          path-To-cladocument: 'https://github.com/${{github.repository}}/${{env.claDocs}}'
          branch: ${{env.auto_branchPrefix}}${{env.auto_branch}}_CLA
          label: ${{env.cla_label}}
          whitelist: join(${{env.auto_whitelist}})
        continue-on-error: true
      # - name: pull-request
      #   uses: repo-sync/pull-request@v2
      #   with:
      #     github_token: ${{ secrets.ACCESS_TOKEN }}
      #     source_branch: ${{env.autoBranchPrefix}}${{env.autoBranch}}_CLA
      #     destination_branch: ${{env.autoDestination}}
      #     pr_title: ${{env.claPRtitle}}
      #     pr_body: ${{env.autoBody}}
      #     pr_label: ${{env.autoLabels}}
      #   continue-on-error: true
