name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]

# Ensures the CLA is signed
jobs:
  CLAssistant:
    name: "CLA Assistant"
    runs-on: ubuntu-latest
    if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA')
    steps:
      - name: "Check-out"
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "CLA Assistant"
        uses: cla-assistant/github-action@v1.3.0-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: '.github/cla.json'
          path-To-cladocument: 'https://github.com/${{github.repository}}/docs/getting-started/contributing/cla.md'
          branch: ${{github.head_ref}}
          label: true
          whitelist: bot*
