name: Issue Management

on:
  issues:
    types: [opened, edited, reopened, assigned, labeled]
  issue_comment:
    types: [created, edited]

jobs:
  labels:
    name: Ensure Lables
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/labels')
    steps:
      - name: Checkout
        uses: actions/checkout@1.0.0
      - name: Create Lables
        uses: lannonbr/issue-label-manager-action@2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  assign_project:
    runs-on: ubuntu-latest
    name: Assign to project
    steps:
      - name: Assign NEW issues to project DevOps
        uses: skeet70/default-project-board-action@v1
        if: github.event.action == 'opened'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          project: 1
      - name: Assign NEW issues to project DevOps
        uses: skeet70/default-project-board-action@v1
        if: contains(github.event.issue.labels.*.name, "Type - Bug")
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          project: 1

  create_issue_branch_job:
    name: Issue Branches
    runs-on: ubuntu-latest
    steps:
    - name: Create Issue Branch
      uses: robvanderleek/create-issue-branch@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  revert-commit:
      runs-on: ubuntu-latest
      if: contains(github.event.comment.body, '/revert')
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Automatic Revert
        uses: srt32/revert@v0.0.1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  CLAssistant:
  name: "CLA Assistant"
  runs-on: ubuntu-latest
  steps:
    - name: "CLA Assistant"
      if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
      # Alpha Release
      uses: cla-assistant/github-action@v1.3.0-alpha
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path-to-signatures: './contributors/cla.json'
        path-To-cladocument: 'https://github.com/${{github.repository}}/contributors/cla.md'
        # branch should not be protected
        branch: 'master'
        whitelist: ${{github.rerepository_owner}},bot*
        empty-commit-flag: false
        blockchain-storage-flag: false

  always_job:
      name: Always run job
      runs-on: ubuntu-latest
      steps:
      - name: Always run
        run: echo "This job is used to prevent the workflow to fail when all other jobs are skipped."
