name: Issue Management

on:
  issues:
    types: [opened, edited, reopened, assigned, labeled]
  issue_comment:
    types: [created, edited]

jobs:
  # Automatically applies labels according to title
  AutoLabel:
    name: Auto Label
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler-title.yml

  # Automatically label sponsors requests
  sponsor:
    name: Sponsor Label
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/is-sponsor-label-action@v1
        with:
          label: Sponsor Request ❤️
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Automatically assigns to project based on tags
  assign_project:
    runs-on: ubuntu-latest
    name: Assign to project
    steps:
      - name: Assign NEW issues to project DevOps
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        if: github.event.action == 'opened'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # GITHUB_PROJECT_URL: https://github.com/orgs/${{github.repository_owner}}/projects/1
          GITHUB_PROJECT_URL: https://github.com/${{github.repository}}/projects/1
          GITHUB_PROJECT_COLUMN_NAME: Requested
      - name: Assign NEW bugs to project bugs
        needs: AutoLabel
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        if: contains(github.event.issue.labels.*.name, 'Type - Bug')
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          #GITHUB_PROJECT_URL: https://github.com/orgs/${{github.repository_owner}}/projects/2
          GITHUB_PROJECT_URL: https://github.com/${{github.repository}}/projects/2
          GITHUB_PROJECT_COLUMN_NAME: New


  # Automatically creates branches based on tags
  create_issue_branch_job:
    needs: AutoLabel
    name: Issue Branches
    runs-on: ubuntu-latest
    steps:
    - name: Create Issue Branch
      uses: robvanderleek/create-issue-branch@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
