name: Command Management

on:
  issue_comment:
    types: [created, edited]

jobs:
  # Automatically reverts commits on request
  revert-commit:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/revert')
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Automatic Revert
        uses: srt32/revert@v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Automatically rebases on request
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  issueCommands:
    name: Issue commands
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/claim')
    steps:
      - uses: technote-space/load-config-action@v1
        with:
          CONFIG_FILENAME: allconfig.yml
      - uses: actions/checkout@v2.3.1
        with:
          ref: ${{github.head_ref}}
      - id: Claim
        if: ( ${{env.commandsEnabled}} == true &&  ${{env.claim}} == true )
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: "CommOps - Accepted"
      - name: Assign claimed issues to ComOps
        if: ( ${{ success() }} && ${{env.commandsEnabled}} == true &&  ${{env.claim}} == true )
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/${{env.projectPath}}/projects/${{env.ComOps}}
          GITHUB_PROJECT_COLUMN_NAME: ${{env.ComOpsColumn}}
