name: Issue Management

on:
  issues:
    types: [opened, edited, reopened, assigned, labeled]
  issue_comment:
    types: [created, edited]

jobs:
  # Automatically applies labels according to title
  AutoLabel:
    name: Auto Label
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/load-config-action@v1
        with:
          CONFIG_FILENAME: allconfig.yml
      - uses: github/issue-labeler@v2.2
        if: ${{env.labelTitle}} == true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ${{env.labelTitlePath}}

  # Automatically label sponsors requests
  sponsor:
    name: Sponsor Label
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/load-config-action@v1
        with:
          CONFIG_FILENAME: allconfig.yml
      - uses: JasonEtco/is-sponsor-label-action@v1
        if: ${{env.labelSponsor}} == true
        with:
          label: ${{env.sponsorLabel}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Automatically assigns to project based on tags
  assign_project:
    name: Assign to project
    runs-on: ubuntu-latest
    needs: AutoLabel
    steps:
      - uses: technote-space/load-config-action@v1
        with:
          CONFIG_FILENAME: allconfig.yml
      - run: if [ ${{env.useOrg}} == true ]; then echo ::set-env name=projectPath::"org/${{github.repository_owner}}" ; else echo ::set-env name=projectPath::"${{github.repository}}" ; fi
      - name: Assign NEW issues to project DevOps
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        if: ( github.event.action == 'opened' && ${{env.assignProjects}} == true )
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/${{env.projectPath}}/projects/${{env.DevOps}}
          GITHUB_PROJECT_COLUMN_NAME: ${{env.DevOpsColumn}}
      - name: Assign NEW bugs to project bugs
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        if: ( contains(github.event.issue.labels.*.name, 'Type - Bug') && ${{env.assignProjects}} == true )
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/${{env.projectPath}}/projects/${{env.Issues}}
          GITHUB_PROJECT_COLUMN_NAME: ${{env.IssuesColumn}}


  # Automatically creates branches based on tags
  create_issue_branch_job:
    needs: AutoLabel
    name: Issue Branches
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/load-config-action@v1
      with:
        CONFIG_FILENAME: allconfig.yml
    - name: Create Issue Branch
      if: ${{env.issueBranch}} == true
      uses: robvanderleek/create-issue-branch@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
