name: Issue Management

on:
  issues:
    types: [opened, edited, assigned]

jobs:
  # Automatically applies labels according to title
  AutoLabel:
    name: Issue Automation
    runs-on: ubuntu-latest
    steps:
      - name: Get Configurations
        uses: Videndum/manage-github-secrets@1.0.0-beta
        with:
          settings: ${{ secrets.SETTINGS }}
          mode: 'environment'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        if: ${{env.profanity_enabled}} == true
        uses: actions/checkout@v2
      - name: Profanity check step
        if: ${{env.profanity_enabled}} == true
        uses: tailaiw/mind-your-language-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - uses: github/issue-labeler@v2.2
        if: ${{env.title_enabled}} == true
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: ${{env.title_path}}
          enable-versioned-regex: ${{env.title_labelVersioned}}
        continue-on-error: true
      - uses: JasonEtco/is-sponsor-label-action@v1
        if: ${{env.sponsor_enabled}} == true
        with:
          label: ${{env.sponsor_label}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - run: if [ ${{env.projects_useOrg}} == true ]; then echo ::set-env name=projectPath::"org/${{github.repository_owner}}" ; else echo ::set-env name=projectPath::"${{github.repository}}" ; fi
      - name: Assign NEW issues to project DevOps
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        if: ( github.event.action == 'opened' && ${{env.projects_enabled}} == true )
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/${{env.projectPath}}/projects/${{env.projects_devOps}}
          GITHUB_PROJECT_COLUMN_NAME: ${{env.projects_devOpsColumn}}
        continue-on-error: true
      - name: Assign NEW bugs to project bugs
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        if: ( contains(github.event.issue.labels.*.name, 'Type - Bug') && ${{env.projects_enabled}} == true )
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/${{env.projectPath}}/projects/${{env.projects_issues}}
          GITHUB_PROJECT_COLUMN_NAME: ${{env.projects_issuesColumn}}
        continue-on-error: true
      - name: Create Issue Branch
        if: ${{env.issueBranch_enabled}} == true
        uses: robvanderleek/create-issue-branch@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
