name: Issue Management

on:
  issues:
    types: [opened, edited, reopened, assigned, labeled]
  issue_comment:
    types: [created, edited]

jobs:
  # Automatically assigns to project based on tags
  assign_project:
    runs-on: ubuntu-latest
    name: Assign to project
    steps:
      - name: Assign NEW issues to project DevOps
        uses: skeet70/default-project-board-action@v1
        if: github.event.action == 'opened'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          project: 1
      - name: Assign NEW bugs to project bugs
        uses: skeet70/default-project-board-action@v1
        if: contains(github.event.issue.labels.*.name, 'Type - Bug')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          project: 2

  # Automatically creates branches based on tags
  create_issue_branch_job:
    name: Issue Branches
    runs-on: ubuntu-latest
    steps:
    - name: Create Issue Branch
      uses: robvanderleek/create-issue-branch@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Automatically reverts commits on request
  revert-commit:
      runs-on: ubuntu-latest
      if: contains(github.event.comment.body, '/revert')
      steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Automatic Revert
        uses: srt32/revert@v0.0.1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Ensures the CLA is signed
  CLAssistant:
    name: "CLA Assistant"
    runs-on: ubuntu-latest
    if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
    steps:
      - name: "Check-out"
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
      - name: "CLA Assistant"
        uses: cla-assistant/github-action@v1.3.0-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: '.github/cla.json'
          path-To-cladocument: 'https://github.com/${{github.repository}}/docs/getting-started/contributing/cla.md'
          branch: 'chore/cla'
          label: true
          whitelist: bot*
          empty-commit-flag: false
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: 'chore/cla'
          destination_branch: "master"
          pr_title: "docs: updating changelog"
          pr_body: ":crown: *An automated PR*"
          pr_label: "skip-changelog"

  # Automatically merges bot pull requests made by CLAssistant
  merge-me:
    name: Merge me!
    needs:
      - CLAssistant
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: github-actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: SQUASH
