name: Project Management
on:
  project_card:
    types: [created, moved]
jobs:
  # Automatically assigns labels based on config ../card-labeler.yml
  triage:
    name: Auto card labeler
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/load-config-action@v1
        with:
          CONFIG_FILENAME: allconfig.yml
      - name: Adjust Lables
        if: ${{env.labelCards}} == true
        uses: technote-space/auto-card-labeler@v1
        with:
          CONFIG_FILENAME: ${{env.labelCardsConfig}}
