name: Pull Request Management

# This workflow automatically lables PR to ensure that all PR's are correct within the release draft.

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  # Not sure why this isn't working, but have raised a ticket
  # Automatically assigns the pull request to project 1
  # assign_project:
  #   runs-on: ubuntu-latest
  #   name: Assign to project
  #   steps:
  #     - name: Assign NEW pull requests to project DevOps
  #       uses: skeet70/default-project-board-action@v1
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         repository: ${{ github.repository }}
  #         issue: ${{ github.event.issue.number }}
  #         project: 1

  # Automatically blocks WIP pull request based on the title
  wip:
    name: Work in progress
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: wip/action@v1.0.0

  # Ensures semantic titles to ensure semantic is achieved when merge is squashed
  semantic:
    name: Semantic Title
    runs-on: ubuntu-latest
    steps:
      - name: Check title
        uses: amannn/action-semantic-pull-request@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Automatically labels based on the branch path
  pr-labeler:
    name: Branch Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/branch-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Automatically labels based on files changed
  path-labeler:
    name: Path Labeler
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        configuration-path: '.github/path-labeler.yml'
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  # Automatically rebases on request
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Automatically checks for conflicts with other pull requests
  conflibot:
    name: Conflict Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Warn potential conflicts
        uses: wktk/conflibot@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # Automatically labels the pull request based on size
  label_sizes:
    name: Pull Request Size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1

      - uses: actions-ecosystem/action-size@v2
        id: size
        with:
          size_xs_label: "Size - XS"
          size_s_label: "Size - S"
          size_m_label: "Size - M"
          size_l_label: "Size - L"
          size_xl_label: "Size - XL"
          size_xxl_label: "Size - XXL"

      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: ${{ steps.size.outputs.stale_labels }}

      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: ${{ steps.size.outputs.new_label }}

  # Ensures the CLA is signed
  CLAssistant:
    name: CLA Assistant
    runs-on: ubuntu-latest
    if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
    steps:
      - name: "Check-out"
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "CLA Assistant"
        uses: cla-assistant/github-action@v1.3.0-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: '.github/cla.json'
          path-To-cladocument: 'https://github.com/${{github.repository}}/docs/getting-started/contributing/cla.md'
          branch: ${{github.head_ref}}
          label: true
          whitelist: bot*

  # Automatically merges bot pull requests made by CLAssistant
  merge-me:
    name: Merge me!
    needs:
      - CLAssistant
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: github-actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: SQUASH
