name: Pull Request Management

# This workflow automatically lables PR to ensure that all PR's are correct within the release draft.

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  # Not sure why this isn't working, but have raised a ticket
  # assign_project:
  #   runs-on: ubuntu-latest
  #   name: Assign to project
  #   steps:
  #     - name: Assign NEW pull requests to project DevOps
  #       uses: skeet70/default-project-board-action@v1
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         repository: ${{ github.repository }}
  #         issue: ${{ github.event.issue.number }}
  #         project: 1

  semantic:
    name: Semantic Title
    runs-on: ubuntu-latest
    steps:
      - name: Check title
        uses: amannn/action-semantic-pull-request@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pr-labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  conflibot:
    name: Conflict Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Warn potential conflicts
        uses: wktk/conflibot@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  label_sizes:
    name: Pull Request Size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-ecosystem/action-size@v2
        id: size
        with:
          size_xs_label: "Size - XS"
          size_s_label: "Size - S"
          size_m_label: "Size - M"
          size_l_label: "Size - L"
          size_xl_label: "Size - XL"
          size_xxl_label: "Size - XXL"

      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: ${{ steps.size.outputs.stale_labels }}

      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: ${{ steps.size.outputs.new_label }}

  CLAssistant:
    name: "CLA Assistant"
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
        uses: cla-assistant/github-action@v1.3.0-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: '/contributors/cla.json'
          path-To-cladocument: 'https://github.com/${{github.repository}}/contributors/cla.md'
          branch: 'master'
          label: true
          whitelist: bot*
          empty-commit-flag: false

  wip:
    name: Work in progress
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: wip/action@v1.0.0
