name: Documentation

on:
  push:
    paths:
      - "docs/**"
  repository_dispatch:
    types: [docs]
  gollum:

jobs:

  # syncs to the github inbuilt wiki
  job-sync-docs-to-wiki:
    name: Sync to wiki
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@master
        with:
          source: docs
          destination: wiki
          token: ${{ secrets.GITHUB_TOKEN }}

  # syncs to an external repository wiki (used for gitbook)
  # sync-downstream:
  #   name: Update wiki repo
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - uses: nxtlvlsoftware/git-subtree-action@master
  #       with:
  #         repo: '${{ github.repository }}-wiki'
  #         path: 'docs'
  #         deploy_key: ${{ secrets.DOWNSTREAM_GITHUB_DEPLOY_KEY }}

  # syncs from the github inbuilt wiki
  job-sync-wiki-to-docs:
    name: Sync from wiki
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@master
        with:
          source: wiki
          destination: docs
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'docs/update-from-wiki'
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: 'master'
          destination_branch: 'docs/update-from-wiki'
          pr_title: "docs: updating docs from wiki"
          pr_body: ":crown: *An automated PR*"
          pr_label: "skip-changelog"
