name: Release Management

on:
  push:
    branches:
      - master

jobs:
  # Ensures all the labels are correct all the time according to ../labels.yml
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v2
        with:
          yaml_file: .github/labels.yml
          skip_delete: false
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Automatically invites users to our team when their pull request is merged
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite contributor to the organization
        uses: lekterable/inclusive-organization-action@v1.1.0
        with:
          organization: Videndum
          team: community
          comment: |
            Well done on getting your first Pull Request merged by our reviewers. The maintainers are proud of you!

            We would like to invite you to become a member of our github community team, which will allow you to get more access to our services & access to contributor only perks.
            Our bot should have already sent the invite. We look forward to you joining the team.
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  # Using the config in ../release-drafter.yml creates release drafts automatically
  update_release_draft:
    name: Create release Draft
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # creates a changelog, commits, pushes, and creates a pull request
  create-changelog:
    name: Create Changelog
    runs-on: ubuntu-18.04
    steps:
      - name: "Check-out"
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
          fetch-depth: 0
      - uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pullRequests: 'true'
          prWoLabels: 'skip-changelog'
          breakingLabels: 'Versioning - BREAKING'
          enhancementLabels: 'Type - Enhancement, Type - Feature'
          bugLabels: 'Type - Fix, Bug - Fixed'
          deprecatedLabels: 'Type - Decrecated'
          removedLabels: 'Type - Removal'
          securityLabels: 'security fix'
          stripGeneratorNotice: "false"
      - name: Commit files
        run: |
          set +e
          ls
          git add CHANGELOG.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "docs(changelog): update" -a
          set -e
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'chore/changelog'
          force: true
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: 'chore/changelog'
          destination_branch: "master"
          pr_title: "docs: updating changelog"
          pr_body: ":crown: *An automated PR*"
          pr_label: "skip-changelog"

  # Automatically merges bot pull requests made by create-changelog
  merge-me:
    name: Merge me!
    needs:
      - create-changelog
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: github-actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: REBASE
