name: Test Management

on:
  push

jobs:
  testEnv:
    name: Test the env loads properly
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/load-config-action@v1
      with:
        CONFIG_FILENAME: allconfig.yml
    - name: Dump
      id: dump
      run: |
        echo ${{ env.claEnabled }}
        echo ${{env.claPush}}
    - name: Dump if
      need: dump
      if: ${{env.claEnabled}} == true
      run: echo if statement worked
