name: Test Management

on:
  pull_request

jobs:
  TestWitout:
    name: tests if env exists
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{env.claPush}}

  testEnv:
    name: Test the env loads properly
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/load-config-action@v1
      with:
        CONFIG_FILENAME: allconfig.yml
    - name: Dump
      id: dump
      run: |
        echo ${{ env.claEnabled }}
        echo ${{env.claPush}}
        if [ ${{env.claPush}} == 'github.head_ref' ]; then echo ::set-env name=claBranch::${{github.head_ref}} ; else echo ::set-env name=claBranch::${{env.claPush}} ; fi
    - name: Dump if
      if: ( ${{ success() }} && ${{env.claEnabled}} == true )
      run: |
        echo if statement worked
        echo ${{env.test}}


  TestAfter:
    name: tests if env exists
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{env.claPush}}
